### PR TITLE
Add a toggle for daily slack reports

### PR DESCRIPTION
**Pull request by will-osborne**
I would like to receive slack notification in the event of failures, however I would not like to receive the daily reports as they clutter the notification channel with no value.
My proposed solution is this configuration option.

### CODE REVIEW

**Comment by will-osborne** [comment]
@zxan1285 Any chance I could get this reviewed?

**Comment by will-osborne** [comment]
Cheers for the approval @zxan1285 
How do I go about getting this merged?

**Comment by will-osborne** [comment]
This still pains me every day.
Any chance I can give this PR a nudge?

**Comment by will-osborne** [comment]
Can I chase this one up?

**Comment by will-osborne** [comment]
@donflopez Are you able to merge?

**Comment by machuga** [comment]
Hi, @will-osborne! 

Thank you so much for the time you spent on this and the patience with our delay in reply.

Unfortunately we will not be adding any new features to these extensions, only bug fixes for the time being. We have refocused our efforts to our new [Log Streaming](https://auth0.com/docs/logs/streams) system to create a more powerful and reliable system for exporting logs from Auth0.

We're sorry for the inconvenience, but I do sincerely the effort you put into making the PR and following up with us.

**Pull request closed without merging**
